In [2]:
import pandas as pd

In [3]:
country = [1,2,3,4]
pd.Series(country)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
runs = [13,24,56,78,100]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [5]:
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']


pd.Series(marks, index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [8]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100  
}

meet_marks = pd.Series(marks, name="Meet na marks")
print(meet_marks)

maths       67
english     57
science     89
hindi      100
Name: Meet na marks, dtype: int64

In [9]:
meet_marks.size

4

In [11]:
meet_marks.dtype

dtype('int64')

In [12]:
meet_marks.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [13]:
meet_marks.values

array([ 67,  57,  89, 100])

In [26]:
subs = pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [27]:
subs.squeeze()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [28]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [31]:
x = pd.Series([12,23,14,52,113,53,14,52])

x

0     12
1     23
2     14
3     52
4    113
5     53
6     14
7     52
dtype: int64

In [32]:
x[1]

23

In [33]:
x[0:4]

0    12
1    23
2    14
3    52
dtype: int64

In [34]:
x.pop(0)

12

In [35]:
x

1     23
2     14
3     52
4    113
5     53
6     14
7     52
dtype: int64

In [51]:
stud_data = [
    [100,80,10], # iq, marks, package
    [90,70,7],
    [120,100,14],
    [80,50,2]    
]
stud_data = pd.DataFrame(stud_data,columns=['iq','marks','package'])

In [39]:
stud_dict = {
    'iq':[100,90,120,80],
    'marks':[80,70,100,50],
    'package':[10,7,14,2]
}

pd.DataFrame(stud_dict)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [2]:
import pandas as pd 
import numpy as np 

mv = pd.read_csv('movies.csv')
ipl = pd.read_csv('ipl-matches.csv')

In [3]:
mv.shape

(1629, 18)

In [4]:
mv.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [5]:
mv.index

RangeIndex(start=0, stop=1629, step=1)

In [6]:
mv.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [7]:
mv.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [11]:
mv.duplicated().sum()

0

In [9]:
data = {
    'name':['Meet','Leet','Keet','Heet','Jeet'],
    'iq':[100,80,10,123,12], # iq, marks, package
    'marks':[90,70,87,53,62],
    'package':[12,8,7,9,6]
    }
data = pd.DataFrame(data)

In [54]:
data.set_index('name',inplace=True)

In [55]:
data

       iq  marks  package
name
Meet  100     90       12
Leet   80     70        8
Keet   10     87        7
Heet  123     53        9
Jeet   12     62        6

In [61]:
data.iloc[0:4]

       iq  marks  package
name
Meet  100     90       12
Leet   80     70        8
Keet   10     87        7
Heet  123     53        9

In [63]:
data.loc['Jeet']

iq         12
marks      62
package     6
Name: Jeet, dtype: int64

In [15]:
L = [1,2,3,4,5]

In [16]:
L.append(3)

In [17]:
L

[1, 2, 3, 4, 5, 3]

In [18]:
L.append([1,3])

In [19]:
L

[1, 2, 3, 4, 5, 3, [1, 3]]

In [20]:
L.extend([1,2,3])

In [21]:
L

[1, 2, 3, 4, 5, 3, [1, 3], 1, 2, 3]

In [9]:
L.clear()

In [10]:
L

[]

In [11]:
del L

In [34]:
L = [1,2,3,4,5,0,11,43,143,12,53,626,112,54,12,57,235,78,34,2364,234463]
sorted(L) # this gives new list

[0,
 1,
 2,
 3,
 4,
 5,
 11,
 12,
 12,
 34,
 43,
 53,
 54,
 57,
 78,
 112,
 143,
 235,
 626,
 2364,
 234463]

In [37]:
print(L)

[0, 1, 2, 3, 4, 5, 11, 12, 12, 34, 43, 53, 54, 57, 78, 112, 143, 235, 626, 2364, 234463]

In [38]:
L.sort()

In [39]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 11,
 12,
 12,
 34,
 43,
 53,
 54,
 57,
 78,
 112,
 143,
 235,
 626,
 2364,
 234463]

In [40]:
L.reverse()

In [41]:
L

[234463,
 2364,
 626,
 235,
 143,
 112,
 78,
 57,
 54,
 53,
 43,
 34,
 12,
 12,
 11,
 5,
 4,
 3,
 2,
 1,
 0]

In [43]:
L = [[0]]*3
L

[[0], [0], [0]]

In [44]:
L[0].append(1)

In [45]:
L

[[0, 1], [0, 1], [0, 1]]

In [48]:
L = [7,8,6,5]
min(L)

5

In [50]:
L = [True, False, True]
all(L)
any(L)

True

In [51]:
t = (1, 2)
a, b = t

In [52]:
a

1

In [53]:
b

2

In [54]:
t = (1, 2, 3)
t*3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [55]:
X = 1,2,3
X

(1, 2, 3)

In [1]:
s1 = {1, 2, 3}
s2 = {2, 3, 4}

s1-s2

{1}

In [2]:
a = "meet"
b = 'sudra'
a+b

'meetsudra'

In [5]:
L=[1,2,3,4,5]
L.pop()

5

In [6]:
L

[1, 2, 3, 4]

In [10]:
s = {}
type(s)

dict

In [11]:
s = set()
type(s)

set

In [20]:
s = {123,5454,253,253,12,5}
s.pop()

5

In [13]:
s

{2, 3, 4, 5}

In [14]:
s.pop()

2

In [22]:
s1 = {1, 2, 3} 
s2 = {4, 5, 6} 
s1.isdisjoint(s2)

True

###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem in which we need to perform concatenation of records from the similarity of initial element. This problem can have applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)] 
Output : [(5, 6, 7, 8), (6, 10), (7, 13)] 
```

In [19]:
test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
unique = []

for i in test_list:
    unique.append(i[0])
unique = set(unique)

result = []
for i in unique:
    result.append([i])
    for j in test_list:
        if j[0] == i:
            result[-1].append(j[1])


print(list(map(tuple,result)))

[(5, 6, 7, 8), (6, 10), (7, 13)]

###`Q2:`
- The original tuple : (1,5,7,8,10)

- resultant tuple after multiplication :
(1.5, 1.5+5.7, 7.5+7.8, and so on)

- multiply with left and right element and add them. Do for every element in the tuple

15
51 + 57
75 + 78
87 + 810
108

5
5
35
56
80

In [43]:
t = (1,5,7,8,10)
t2 = []

for i in range(0,len(t)):
    if i==0:
        t2.append((t[i] * t[i+1]))
    elif i==len(t)-1:
        t2.append((t[i] * t[i-1]))
    else:
        t2.append((t[i] * t[i+1]) + (t[i]*t[i-1]))

t2

[5, 40, 91, 136, 80]

###`Q3`: Check is tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```

In [54]:
t1 = (1,2,3,0)
t2 = (1,1,2,3)

if len(t1) != len(t2):
    print("2 tuples are not same")
else:
    is_same = True
    for i in range(len(t1)):
        if t1[i] != t2[i]:
            is_same=False
            break
    if is_same:
        print("Tuples are same")
    else:
        print("Tuples are not same")

Tuples are not same

###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```

In [65]:
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]
list_count = 0
tuple_count = 0
set_count = 0
for i in range(len(list1)):
    if type(list1[i]) == list:
        list_count += 1
    if type(list1[i]) == tuple:
        tuple_count += 1
    else:
        set_count += 1

print("List-",list_count)
print("Set-",set_count)
print("Tuples-",tuple_count)

List- 2
Set- 4
Tuples- 1

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```

In [68]:
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

list(set(ar1) & set(ar2) & set(ar3))

[80, 20]

###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```

In [72]:
vowels = ['a','e','i','o','u','A','E','I','O','U']
u = []

Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
for i in vowels:
    if i in Str1:
        u.append(i)
    
len(set(u))

6

### `Q3:` Write a program to Check if a given string is binary string of or not. 

A string is said to be binary if it's consists of only two unique characters.

Take string input from user. 

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```

In [74]:
Str = "Hello brother"
binary = ['1','0']

for i in Str: 
    is_binary = True

    if i != 0 or i != 1:
        is_binary = False
        break

    if is_binary :
        print("str is binary")
    else:
        print("str is not binary")

### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```

In [10]:
my_list = [[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]

my_set = set()

for i in my_list[:]:
    my_set.update(set(i))

In [12]:
list(my_set)

[1, 2, 3, 4, 5, 6, 7, 9]

### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```

In [14]:
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}

list(lst1.intersection(lst2))

[9, 10, 4, 5]

In [21]:
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}

union = lst1.union(lst2)
print(union)

common = [i for i in union if i in lst1 and i in lst2]
print(common)

{4, 5, 36, 9, 10, 45, 78, 15, 47, 87, 23, 56, 26}
[4, 5, 9, 10]

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```

In [42]:
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
max_count = -1
result_key = None
for key, value in test_dict.items():
    value_count = len(set(value))
    if value_count>max_count:
        max_count = value_count
        result_key = key

print(result_key)

CampusX

In [2]:
records = [["P1", "Diabetes"], ["P2", "Flu"], ["P1", "Diabetes"]]

emaj = list(set(tuple(i) for i in records))
emaj

[('P2', 'Flu'), ('P1', 'Diabetes')]

In [33]:
codes = "ICD10, ICD9, ICD10, ICD11, ICD9, ICD10"
codes_list = [c.strip() for c in codes.split(',')]

freq_dict = {}
for i in codes_list:
    if i in freq_dict:
        freq_dict[i] = freq_dict[i] + 1
    else:
        freq_dict[i] = 1

max_code = max(freq_dict,key=freq_dict.get)

In [39]:
data = {"ID101": "Cold", "ID102": "Flu", "ID103": "Injury"}

for key, value in data.items(): 
    if value == 'Flu':
        print(key)

ID102

In [40]:
result=[k for k,v in data.items() if v == 'Flu']
result

['ID102']

In [41]:
meds = [("Paracetamol", 500), ("Ibuprofen", 200), ("Paracetamol", 250)]

doses = {}
for i in meds:
    if i[0] in doses:
        doses[i[0]] +=1
    else:
        doses[i[0]] = 1

doses

{'Paracetamol': 2, 'Ibuprofen': 1}

In [ ]:
meds = [("Paracetamol", 500), ("Ibuprofen", 200), ("Paracetamol", 250)]

for name,mg in meds:
    print(name,mg)

Paracetamol 500
Ibuprofen 200
Paracetamol 250

In [53]:
meds = [("Paracetamol", 500), ("Ibuprofen", 200), ("Paracetamol", 250)]

doses = {}
for name,mg in meds:
    doses[name] = doses.get(name,0) + mg
doses

{'Paracetamol': 750, 'Ibuprofen': 200}

In [60]:
a = [[1,2], [3,4]]
# convert to a flat list brother 

print([j for i in a for j in i])

[1, 2, 3, 4]

In [64]:
patients = ["A", "B", "C"]
status = ["Discharged", "Admitted", "Discharged"]

dictionary = {}
discharged_one_line = []
for patients,status in zip(patients,status):
    dictionary[patients] = status

for k,v in dictionary.items():
    if v == 'Discharged':
        discharged_one_line.append(k)

discharged_one_line

['A', 'C']

In [62]:
dictionary

{'A': 'Discharged', 'B': 'Admitted', 'C': 'Discharged'}

In [76]:
# get a list of only the names (keys) of patients whose BP is greater than 130

vitals = {"P1": {"BP": 120, "HR": 72}, "P2": {"BP": 140, "HR": 80}, "P3": {"BP": 110, "HR": 65}}

for k,v in vitals.items() : 
    if v['BP'] > 130:
        print(v)

{'BP': 140, 'HR': 80}

In [78]:
[k for k,v in vitals.items() if v['BP']>130]

['P2']

In [92]:
results = [120, None, 140, 110, None, 130]
clean_results = []
# remove null values 

for i in results: 
        if i is not None:
            clean_results.append(str(i) + ' ' + 'mmHg')

In [93]:
print(results)
print(clean_results)

[120, None, 140, 110, None, 130]
['120 mmHg', '140 mmHg', '110 mmHg', '130 mmHg']

In [94]:
[str(i) + ' ' + 'mmHg' for i in results if i is not None]

['120 mmHg', '140 mmHg', '110 mmHg', '130 mmHg']

In [101]:
class Patient:
    def __init__(self,name,age):
        self.name = name 
        self.age = age 

    def is_vulnerable(self):
        if self.age > 60:
            return True
        else:
            return False

In [115]:
p1 = Patient('Meet',7)
p2 = Patient('Heet',77)
p3 = Patient('Jeet',66)
p4 = Patient('Neel',33)
p5 = Patient('Jay',22)

L = [p1,p2,p3,p4,p5]
[i.name for i in L if i.is_vulnerable()]

['Heet', 'Jeet']

'Heet'

In [1]:
a = "meet"
b = "sudra"
a+b

'meetsudra'

In [6]:
a = '1'

In [7]:
a.join('meet')

'm1e1e1t'

In [9]:
del a

In [24]:
a = [1,2,3,4]
a.extend({5:6,7:8})

In [25]:
a

[1, 2, 3, 4, 5, 7]

In [26]:
a.pop()

7

In [27]:
a.remove(3)

In [28]:
a

[1, 2, 4, 5]

In [29]:
a.pop(2)

4

In [30]:
a.clear()

In [38]:
a = [4,6,5,66,235,21,5,676,235]
a.sort()

In [39]:
sorted(a)

[4, 5, 5, 6, 21, 66, 235, 235, 676]

In [40]:
b = a.copy()

In [41]:
b

[4, 5, 5, 6, 21, 66, 235, 235, 676]

In [42]:
print(id(b))
print(id(b))

4473248832
4473248832

In [51]:
a = [1,2,3,4]
a = b
print(id(a))

4473248832

In [52]:
print(id(b))

4473248832

In [54]:
a.count(4)

1

In [55]:
b = a.copy()
b

[4, 5, 5, 6, 21, 66, 235, 235, 676]

In [56]:
print(id(a))
print(id(b))

4473248832
4473964224

In [63]:
a.insert(2,0)

In [64]:
a

[4, 5, 0, 0, 0, 1, 5, 6, 21, 66, 235, 235, 676]

In [65]:
list1 = [10, 20, 30]
list2 = list1.copy()
list2.append(40)

print(list1 == list2) 
print(list1 is list2)

False
False

In [71]:
a = (1,2,3,4)
a.index(2)

1

In [72]:
b = (5,6,7,8)
a+b

(1, 2, 3, 4, 5, 6, 7, 8)

In [101]:
a = {1,2,3}
a.add(4)

In [102]:
a.update((5,6,7))

In [103]:
a

{1, 2, 3, 4, 5, 6, 7}

In [100]:
a.pop()

7

In [104]:
a.remove(2)

In [105]:
a

{1, 3, 4, 5, 6, 7}

In [106]:
a.clear()

In [107]:
a

set()

In [108]:
my_dict = {'a':'1','b':'2','c':'3'}
my_dict.items()

dict_items([('a', '1'), ('b', '2'), ('c', '3')])

In [109]:
my_dict.values()

dict_values(['1', '2', '3'])

In [52]:
A1 =[100,100,100,-10]
D1 =["2020-12-31", "2020-12-22", "2020-12-03", "2020-12-29"]

def calculate_bal(a,b):
    months = ['01','02','03','04','05','06','07','08','09','10','11','12']
    transaction_months = list({i.split('-')[1] for i in b})
    # check for the months where no transactions happened, we can directly deduct -5 
    no_transaction_months = sorted(set(months).symmetric_difference(set(transaction_months)))
    bank_balance =  sum(a)
    maintenance_fee = 5 

    # check for months who had atleast 3 negative transactions + sum of these trans was less then -100
    for m in transaction_months:
        amounts_this_month = [a[i] for i in range(len(a)) if b[i].split('-')[1]== m]
        negative_transactions = 0
        negative_transactions_sum = 0
        for i in amounts_this_month:
            if i<0:
                negative_transactions+=1
                negative_transactions_sum += i
            else:
                continue
        if not (negative_transactions>=3 and negative_transactions_sum <= -100):
            bank_balance -= 5

    bank_balance = bank_balance -  len(no_transaction_months)*5 # at the end we can directly remove all the non-transaction-month fine
    print(bank_balance)

calculate_bal(A1,D1)

230

In [56]:
A2 =[180, -50 , -25 , -25]
D2 = ["2020-01-01", "2020-01-01","2020-01-01", "2020-01-31"]
calculate_bal(A2,D2)

A3 = [1,-1,0,-105, 1]
D3 =["2020-12-31", "2020-04-04", "2020-04-04" , "2020-04-14", "2020-07-12"]
calculate_bal(A3,D3)

A4 = [100,100,-10,-20,-30]
D4 =["2020-01-01", "2020-02-01", "2020-02-11", "2020-02-05", "2020-02-08"]
calculate_bal(A4 ,D4)

A5 =[-60,60, -40 , -20]
D5 =["2020-10-01", "2020-02-02", "2020-10-10", "2020-10-30"]
calculate_bal(A5 ,D5 )

25
-164
80
-115

In [ ]:
[12:34]
[21:43]
[22:33]

In [85]:
from itertools import permutations
a = [4,1,3,7]
hour_one = [0,1,2]
hour_two = [0,1,2,3,4,5,6,7,8,9]
min_one = [0,1,2,3,4,5]
min_two = [0,1,2,3,4,5,6,7,8,9]


perm_list = list(set(permutations(a)))
for i in perm_list:
    if i[0] in hour_one:
        h1 = i[0]
        if i[1] in hour_two:
            h2 = i[1]
            if i[2] in min_one:
                m1 = i[2]
                if i[3] in min_two:
                    m2 = i[3]
                    print(f"{h1}{h2}:{m1}{m2}")
    else:
        continue

17:34
17:43
14:37
13:47

In [91]:
from itertools import permutations
a = [1,2,3,5]

def clock():
    my_perm = list(set(permutations(a)))
    time = {}
    for i in my_perm:
        h1,h2,m1,m2 = i[0],i[1],i[2],i[3]
        hour = h1*10+h2
        minute = m1*10+m2

        if hour<24 and minute<60:
            time[hour] = minute
    return len(time)

R = "BAABA", 
V = [2, 4, 1, 1, 2]

A --> B (2) 
B_bal =  + 2
A_bal =  - 2 (needs 2)

B --> A (4)
B_bal =  + 2 - 4 (needs 2)
A_bal =  - 2 + 4

B --> A (1)
B_bal =  + 2 - 4 - 1 (needs 3)
A_bal =  - 2 + 4 + 1

A --> B (1)
B_bal =  + 2 - 4 - 1 + 1 (needs 2)
A_bal =  - 2 + 4 + 1 - 1

B -- A (2)
B_bal =  + 2 - 4 - 1 + 1 - 2 (needs 4)
A_bal =  - 2 + 4 + 1 - 1 + 2

In [135]:
R = "BAABA"
V = [2,4,1,1,2]

def min_bal(p,a):
    A_bal = 0
    B_bal = 0

    A_min_bal = 0
    B_min_bal = 0 

    for rec,amount in zip(p,a):
        if rec == 'A':
            A_bal += amount
            B_bal -= amount
        else :
            B_bal += amount 
            A_bal -= amount 

        if A_bal<0:
            A_min_bal = max(A_min_bal,-A_bal)
        if B_bal<0:
            B_min_bal = max(B_min_bal,-B_bal)

    return [A_min_bal,B_min_bal]

min_bal(R,V)

[2, 4]

In [ ]:
S = 'CBABD'
stack = []

def solution(S):
    for i in S:
        if stack:
            top = stack[-1]
            if (top=='A' and i=='B') or (top=='B' and i=='A'):
                stack.pop()
                continue
            if (top=='C' and i=='D') or (top=='D' and i=='C'):
                stack.pop()
                continue
        stack.append(i)
    return ''.join(stack)

solution(S)

'CBD'

In [143]:
stack

['A', 'C', 'D', 'B']

In [205]:
def binary_gaps(a):
    bin_str = bin(a)[2:].strip('0')
    gaps = bin_str.split('1')
    return len(max(gaps)) if gaps else 0

binary_gaps(55555555555)

7

In [193]:
for i in range(0,100):
    binary_gaps(i)

In [208]:
def solution(S):
    bin_str = bin(S)[2:].strip('0')
    gaps = bin_str.split('1')
    return len(max(gaps)) if gaps else 0

solution(5)

1

In [214]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]
def equilibrium_index(A):
    index = []
    for i in range(0,len(A)):
        if sum(A[:i]) == sum(A[i+1:]):
            index.append(A[i])
        else:
            continue
    if len(index)==0:
        return -1
    return index

equilibrium_index(A)

[3, 5, 1]

In [2]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]

def eqilibrium(A):
    total_sum = sum(A)
    left_sum = 0

    for i in range(len(A)):
        right_sum = total_sum-left_sum-A[i]
        if right_sum == left_sum:
            return A[i]
        else:
            left_sum = left_sum + A[i]
    return -1

eqilibrium(A)

3

In [4]:
A = [9, 3, 9, 3, 9, 7, 9]

def uni(A):
    A_uni = list(set(A))
    for i in A_uni:
        count = A.count(i)
        if count>1:
            continue
        else:
            return i
        
uni(A)

7

In [10]:
array = [1,2,3,4,5]

In [14]:
rotate_by = 4

length_of_array = len(array)
rotate_by = rotate_by % length_of_array
print(array[-rotate_by:]+array[:-rotate_by])

[2, 3, 4, 5, 1]

In [ ]:
array = [4, 1, 2, 1, 2]

def single(array):
    res = 0
    for i in array:
        res = res ^ i
        return res
    
single(array)

4

In [24]:
a = [4, 1, 2]
for i in range(1,max(a)):
    if i in a:
        continue
    else:
        print(i,"is missing and hence no permutation")

3 is missing and hence no permutation

In [30]:
def binary_gaps(a):
    binary_string = bin(a)[2:].strip('0')
    gaps = binary_string.split('1')
    return len(max(gaps, key=len)) if gaps else 0
binary_gaps(5555)

2

In [29]:
bin(5555)[2:].strip('0')

'1010110110011'

In [ ]:
a = [2,3,4,5,3,4,5,6,6,7,7,8,8]

def oddoccurance(a):
    res = 0
    for i in a:
        res = res ^ i
    return res
    
oddoccurance(a)

2

In [39]:
array = [2,3,4,5,6]

s = 2

s = s % len(array)
print(array[-s:]+ array[:-s])

[5, 6, 2, 3, 4]

In [46]:
import math
X = 10 
Y = 85
steps = 30 

math.ceil((Y-X)/steps)

3

In [53]:
(Y-X+steps-1)//steps

3

In [74]:
from itertools import permutations
A = [2, 3, 1, 5]

def missing(A):
    max_el = max(A)
    min_el = min(A)

    for i in range(min_el,max_el):
        if i in A:
            print(i)
            continue
        else:
            return i
        
missing(A)

1
2
3

4

In [ ]:
A = [2, 3, 1, 5]
def missing(A):
    sum = 0
    expected_sum = 0
    for i in A:
        sum = sum + i
    for j in range(1,len(A)+2):
        expected_sum = expected_sum + j
    return expected_sum - sum
    
missing(A)

4

In [67]:
sum= 0
for i in range(11):
    sum = sum + i
print(sum)

55

In [72]:
a = [1,2,3,4,5,6,7,8,10]
summ = 0
for i in a:
    summ = summ + i 
print(summ)

46

In [73]:
55-46

9

In [79]:
def solution(A,k): 
        k = k % len(A)
        return A[-k:]+A[:-k]

A = [2,3,4,5,6,7]
solution(A,7)

# [,2,,,,]

[7, 2, 3, 4, 5, 6]

In [80]:
7 % 6

1

In [81]:
1 % 6

1

In [ ]:
A = [9,3,9,3,9,7,9]

def solution(A):
    uni_A = list(set(A))
    non_duplicate = []
    for i in uni_A:
        if A.count(i)>1:
            continue
        else:
            return i

In [ ]:
A = [9,3,9,3,9,7,9]
def solution(A):
    res = 0
    for i in A:
        res = res ^ i
    return res
solution(A)

9

In [88]:
X = 10
Y = 85
D = 30

(Y-X+D-1)//D

3

In [91]:
A = [1,2,3,5]
for i in range(1,len(A)+2):
    print(i)

1
2
3
4
5

In [108]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]
nos=[]
for i in range(0,len(A)):
    if sum(A[:i]) == sum(A[i+1:]):
        nos.append(A[i])
    else:
        continue

print(nos)

[3, 5, 1]

In [112]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]
def solution(A):
    nos=[]
    if len(A) == 0:
        return -1
    for i in range(0,len(A)):
        if sum(A[:i]) == sum(A[i+1:]):
            nos.append(A[i])
        else:
            continue
    return nos
solution(A)

[3, 5, 1]

In [114]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]
total_sum = sum(A)
left_sum = 0
def solution(A):
    for i in range(len(A)): 
        right_sum = total_sum-left_sum-A[i]
        if left_sum == right_sum:
            return A[i]
        else:
            continue

In [118]:
A = [3,1,2,4,3]
def solution(A):
    results = []
    for i in range(len(A)):
        if sum(A[:i]) == sum(A[i+1:]):
            results.append(A[i])
        else:
            continue
    if len(results) == 0:
        return -1
    else:
        return results
solution(A)

-1

In [124]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]
def solution(A):
    total_sum = sum(A)
    left_sum = 0
    results = []

    for i in range(len(A)):
        right_sum = total_sum-left_sum-A[i]
        if left_sum == right_sum:
            results.append(A[i])
        
        left_sum += A[i]

    return results if results else -1
solution(A)

[3, 5, 1]

In [125]:
A = [3,1,2,4,3]

def solution(A):
    results = []
    for i in range(len(A)):
        if sum(A[:i]) == sum(A[i+1:]):
            results.append(A[i])
            return A[i]
    if len(results) == 0:
        return 1
        
solution(A)

1

In [ ]:
pos = 0 # here right now
X = 5
pos_later = X+1 # to reach

A = [1,3,1,4,2,3,5,4]

pos = 0 # here right now
X = 5
pos_later = X+1 # to reach 

list A k sare elements positions he and usk indexes time he

sec 0 frog was at position 1 
sec 1 frog was at position 3 
sec 2 frog was at position 1 (ignore)
sec 3 frog was at position 4 
sec 4 frog was at position 2 
sec 5 frog was at position 3 (ignore)
sec 6 frog was at position 5 
sec 7 frog was at position 4 (ignore)

In [ ]:
A = [1,3,1,4,2,3,5,4]
def frog_sec(A):
    A_str = ''
    for i in A:
        A_str+=str(i)
    postions = set(A)
    postions

    A_str.rfind(str(max(postions)))
frog_sec(A)

6

In [136]:
A = [1,3,1,4,2,3,5,4]
def solution(A,X):
    river_positions = set()
    for time,pos in enumerate(A):
        if pos<=X:
            river_positions.add(pos)
        if len(river_positions) == X:
            return time
solution(A,5)

6

In [140]:
A = [4,1,2,3,5,1,3,1]

def solution(A):
    for i in range(1,len(A)+1):
        if i in A:
            continue
        else:
            return i
solution(A)

6

In [147]:
A = [3,4,4,6,1,4,4]
counters = [0,0,0,0,0]

for j in A:
    for i in range(1,len(counters)+1):
        if i == j:
            counters[i-1] += 1
        if i==len(counters)+1 and j==len(counters)+1:
            [i+1 for i in counters] 
print(counters)

[1, 0, 1, 4, 0]

In [149]:
A = [0, 1, 0, 1, 1]

stack = []
for i in A:
    if stack :
        if (stack[-1] == 0 and i == 1) or (stack[-1] == 1 and i == 0):
            stack.pop()
        else:
            continue
    stack.append(i)

In [155]:
A = ['A', 'B', 'A', 'B', 'C']

stack = []
for i in A:
    if stack :
        if (stack[-1] == 'A' and i =='B') or (stack[-1] == 'B' and i == 'A'):
            stack.pop()
        else:
            continue
    stack.append(i)

In [156]:
stack

['B']

In [169]:
A = [0, 1, 0, 1, 1]
count = 0
for i in range(len(A)): 
    for j in A[i+1:]:
        if (A[i]==0 and A[j]==1) or (A[i]==1 and A[j]==0):
            count += 1
        else:
            continue

In [170]:
count

6

In [172]:
cars = [0, 1, 0, 1, 1]
def solution(cars):
    zeros = 0 
    pairs = 0

    for i in cars:
        if i == 0:
            zeros += 1
        else:
            pairs = pairs + zeros 

    return pairs 
solution(cars)

5

In [173]:
a = {1,2,3}
len(a)

3

In [176]:
from itertools import permutations

A = [-3,1,2,-2,5,6]
perm = set(permutations(A,3))
len(perm)

120

In [177]:
from itertools import permutations

A = [-3,1,2,-2,5,6]
perm = list(set(permutations(A,3)))
all = []
for i in perm :
    mul = 1
    for j in i:
        mul = mul*j
        all.append(mul)
print(max(all))

60

In [181]:
A = [-3,1,2,-2,5,6]
def solution(A):
    sorted_A = sorted(A)
    for i in range(len(sorted_A)):
        mul1 = sorted_A[-1]*sorted_A[-2]*sorted_A[-3]
        mul2 = sorted_A[0]*sorted_A[1]*sorted_A[-1]
    return max(mul1,mul2)
solution(A)

60

In [ ]:
sorted(A)

[-3, -2, 1, 2, 5, 6]

In [ ]:
A = [10,50,5,1]

def solution(A):
    for i in range(1,len(A)+1):
        if (A[0] + A[1] > A[2]) and (A[0] + A[2] > A[1]) and (A[1] + A[2] > A[0]):
            return 1 
        A = A[1:]+A[:1]
        i += 1
    return 0
solution(A)

1

In [1]:
A = [3,8,9,7,6]
K = 3
def solution(A, K):
    K = K%len(A)
    return A[-K:]+A[:-K]

solution(A,K)

[9, 7, 6, 3, 8]

In [5]:
A = [9,3,9,3,9,7,9]
def solution(A):
    result = 0
    for i in A: 
        result = result ^ i
    return result

solution(A)

7

In [11]:
X = 10
Y = 85
D = 30
def solution(X,Y,D):
    return (Y-X+D-1)//D

solution(X,Y,D)

3

In [13]:
A = [2,3,1,5]
def solution(A):
    for i in range(1,len(A)+1):
        if i in A:
            continue
        else:
            return i
solution(A)

4

In [24]:
A = [-1, 3, -4, 5, 1, -6, 2, 1]

def solution(A):
    total_sum = sum(A)
    left_sum = 0
    my_list = []
    for i in range(len(A)):
        right_sum = total_sum-left_sum-A[i]
        if left_sum == right_sum:
            my_list.append(A[i])
        
        left_sum += A[i]
    if len(my_list) == 0:
        return -1
    return my_list
solution(A)

[3, 5, 1]

In [32]:
import numpy as np
A = [-1, 3, -4, 5, 1, -6, 2, 1]

def solution(A):
    total_sum = sum(A)
    left_sum = 0
    my_list = []
    distances = []
    for i in range(len(A)):
        right_sum = total_sum-left_sum-A[i]
        if left_sum == right_sum:
            my_list.append(A[i])
        distances.append(np.abs(left_sum-right_sum))
        left_sum += A[i]
    if len(my_list) == 0:
        return -1
    return distances

solution(A)

[2, 0, 1, 0, 6, 1, 3, 0]

In [25]:
A = [2,3,1,5]
sum = 0
expected_sum = 0
for i in A:
    sum= sum+i
for j in range(max(A)+1):
    expected_sum = expected_sum+j

sum-expected_sum

-4