In [2]:
import pandas as pd

In [3]:
country = [1,2,3,4]
pd.Series(country)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
runs = [13,24,56,78,100]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [5]:
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']


pd.Series(marks, index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [8]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100  
}

meet_marks = pd.Series(marks, name="Meet na marks")
print(meet_marks)

maths       67
english     57
science     89
hindi      100
Name: Meet na marks, dtype: int64

In [9]:
meet_marks.size

4

In [11]:
meet_marks.dtype

dtype('int64')

In [12]:
meet_marks.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [13]:
meet_marks.values

array([ 67,  57,  89, 100])

In [26]:
subs = pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [27]:
subs.squeeze()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [28]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [31]:
x = pd.Series([12,23,14,52,113,53,14,52])

x

0     12
1     23
2     14
3     52
4    113
5     53
6     14
7     52
dtype: int64

In [32]:
x[1]

23

In [33]:
x[0:4]

0    12
1    23
2    14
3    52
dtype: int64

In [34]:
x.pop(0)

12

In [35]:
x

1     23
2     14
3     52
4    113
5     53
6     14
7     52
dtype: int64

In [51]:
stud_data = [
    [100,80,10], # iq, marks, package
    [90,70,7],
    [120,100,14],
    [80,50,2]    
]
stud_data = pd.DataFrame(stud_data,columns=['iq','marks','package'])

In [39]:
stud_dict = {
    'iq':[100,90,120,80],
    'marks':[80,70,100,50],
    'package':[10,7,14,2]
}

pd.DataFrame(stud_dict)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [2]:
import pandas as pd 
import numpy as np 

mv = pd.read_csv('movies.csv')
ipl = pd.read_csv('ipl-matches.csv')

In [3]:
mv.shape

(1629, 18)

In [4]:
mv.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [5]:
mv.index

RangeIndex(start=0, stop=1629, step=1)

In [6]:
mv.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [7]:
mv.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [11]:
mv.duplicated().sum()

0

In [9]:
data = {
    'name':['Meet','Leet','Keet','Heet','Jeet'],
    'iq':[100,80,10,123,12], # iq, marks, package
    'marks':[90,70,87,53,62],
    'package':[12,8,7,9,6]
    }
data = pd.DataFrame(data)

In [54]:
data.set_index('name',inplace=True)

In [55]:
data

       iq  marks  package
name
Meet  100     90       12
Leet   80     70        8
Keet   10     87        7
Heet  123     53        9
Jeet   12     62        6

In [61]:
data.iloc[0:4]

       iq  marks  package
name
Meet  100     90       12
Leet   80     70        8
Keet   10     87        7
Heet  123     53        9

In [63]:
data.loc['Jeet']

iq         12
marks      62
package     6
Name: Jeet, dtype: int64

In [15]:
L = [1,2,3,4,5]

In [16]:
L.append(3)

In [17]:
L

[1, 2, 3, 4, 5, 3]

In [18]:
L.append([1,3])

In [19]:
L

[1, 2, 3, 4, 5, 3, [1, 3]]

In [20]:
L.extend([1,2,3])

In [21]:
L

[1, 2, 3, 4, 5, 3, [1, 3], 1, 2, 3]

In [9]:
L.clear()

In [10]:
L

[]

In [11]:
del L

In [34]:
L = [1,2,3,4,5,0,11,43,143,12,53,626,112,54,12,57,235,78,34,2364,234463]
sorted(L) # this gives new list

[0,
 1,
 2,
 3,
 4,
 5,
 11,
 12,
 12,
 34,
 43,
 53,
 54,
 57,
 78,
 112,
 143,
 235,
 626,
 2364,
 234463]

In [37]:
print(L)

[0, 1, 2, 3, 4, 5, 11, 12, 12, 34, 43, 53, 54, 57, 78, 112, 143, 235, 626, 2364, 234463]

In [38]:
L.sort()

In [39]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 11,
 12,
 12,
 34,
 43,
 53,
 54,
 57,
 78,
 112,
 143,
 235,
 626,
 2364,
 234463]

In [40]:
L.reverse()

In [41]:
L

[234463,
 2364,
 626,
 235,
 143,
 112,
 78,
 57,
 54,
 53,
 43,
 34,
 12,
 12,
 11,
 5,
 4,
 3,
 2,
 1,
 0]

In [43]:
L = [[0]]*3
L

[[0], [0], [0]]

In [44]:
L[0].append(1)

In [45]:
L

[[0, 1], [0, 1], [0, 1]]

In [48]:
L = [7,8,6,5]
min(L)

5

In [50]:
L = [True, False, True]
all(L)
any(L)

True

In [51]:
t = (1, 2)
a, b = t

In [52]:
a

1

In [53]:
b

2

In [54]:
t = (1, 2, 3)
t*3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [55]:
X = 1,2,3
X

(1, 2, 3)

In [1]:
s1 = {1, 2, 3}
s2 = {2, 3, 4}

s1-s2

{1}

In [2]:
a = "meet"
b = 'sudra'
a+b

'meetsudra'

In [5]:
L=[1,2,3,4,5]
L.pop()

5

In [6]:
L

[1, 2, 3, 4]

In [10]:
s = {}
type(s)

dict

In [11]:
s = set()
type(s)

set

In [20]:
s = {123,5454,253,253,12,5}
s.pop()

5

In [13]:
s

{2, 3, 4, 5}

In [14]:
s.pop()

2

In [22]:
s1 = {1, 2, 3} 
s2 = {4, 5, 6} 
s1.isdisjoint(s2)

True